/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://ro2ne5eti5cwzn5m5obxccfcei.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-axol5rkco5g5rkpozbhbf6b4ky",
    "aws_cloud_logic_custom": [
        {
            "name": "floraPayment",
            "endpoint": "https://vwdxk2oqi0.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        }
    ],
    "aws_cognito_identity_pool_id": "us-east-1:d093aebb-8daa-447a-a141-b7958c52f132",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_Tm4i9F7oE",
    "aws_user_pools_web_client_id": "1i99baijsm3potneph4ilj8knd",
    "oauth": {}
};


export default awsmobile;
